<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
				xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="#all"
				xmlns:oxy="http://www.oxygenxml.com/functions"
				xmlns:relpath="http://dita2indesign/functions/relpath"
				xmlns:whc="http://www.oxygenxml.com/webhelp/components"
				xmlns:html="http://www.w3.org/1999/xhtml"
				xmlns:oxygen="http://www.oxygenxml.com/functions"
				xpath-default-namespace="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml"
				version="2.0">

	<xsl:import href="commonComponentsExpander.xsl"/>

	<xsl:param name="TRANSTYPE"/>

	<xsl:template match="whc:webhelp_topic_content" mode="copy_template">
		<xsl:param name="ditaot_topicContent" tunnel="yes"/>
		<xsl:choose>
			<xsl:when test="exists($ditaot_topicContent)">
				<div>
					<xsl:call-template name="generateComponentClassAttribute">
						<xsl:with-param name="compClass">wh_topic_content</xsl:with-param>
					</xsl:call-template>
					<!-- Copy attributes -->
					<xsl:copy-of select="@* except @class"/>

					<!-- Copy topic content without the related links section. -->
					<!-- Try to copy the 'main' element. Generally, it is generated by DITA-OT 2.x  -->
					<xsl:variable name="topicContent2_0" select="$ditaot_topicContent//body//main"/>
					<xsl:choose>
						<xsl:when test="exists($topicContent2_0)">
							<xsl:apply-templates select="$topicContent2_0" mode="copy-topic-content"/>
						</xsl:when>
						<xsl:otherwise>
							<!-- For DITA-OT 1.8 copy the content of div[@id = 'topicContent'] -->
							<xsl:apply-templates select="$ditaot_topicContent//body//div[@id = 'topicContent']/node()" mode="copy-topic-content"/>
						</xsl:otherwise>
					</xsl:choose>
				</div>
			</xsl:when>
			<xsl:otherwise>
				<xsl:message>Cannot expand the 'webhelp_topic_content' component.</xsl:message>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>

	<xsl:template match="div[@id='wh_topic_body'][contains(@class, 'col-')]" mode="fix-content-width">
		<xsl:param name="contentArea" tunnel="yes"/>
		<xsl:variable name="publicationToc" select="$contentArea//div[contains(@class, 'wh_publication_toc')]"/>
		<xsl:variable name="topicToc" select="$contentArea//div[contains(@class, 'wh_topic_toc')]"/>

		<xsl:variable name="newClassValue">
			<xsl:choose>
				<xsl:when test="exists($publicationToc)">
					<xsl:value-of select="@class"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:variable name="nonBootstrapClassValues">
						<xsl:for-each select="tokenize(@class, ' ')">
							<xsl:if test="not(starts-with(.,'col-'))">
								<xsl:value-of select="concat(' ', .)"/>
							</xsl:if>
						</xsl:for-each>
					</xsl:variable>
					<xsl:value-of select="concat('col-lg-12 col-md-12 col-sm-12 col-xs-12', $nonBootstrapClassValues)"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>

		<xsl:copy>
			<xsl:attribute name="class" select="$newClassValue"/>
			<xsl:apply-templates select="@* except @class" mode="#current"/>
			<xsl:apply-templates select="node()" mode="#current"/>
		</xsl:copy>
	</xsl:template>

	<xsl:template match="div[@id='topic_content'][contains(@class, 'col-')]" mode="fix-content-width">
		<xsl:param name="contentArea" tunnel="yes"/>
		<xsl:variable name="topicToc" select="$contentArea//div[contains(@class, 'wh_topic_toc')]"/>

		<xsl:variable name="newClassValue">
			<xsl:choose>
				<xsl:when test="exists($topicToc)">
					<xsl:value-of select="@class"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:variable name="nonBootstrapClassValues">
						<xsl:for-each select="tokenize(@class, ' ')">
							<xsl:if test="not(starts-with(.,'col-'))">
								<xsl:value-of select="concat(' ', .)"/>
							</xsl:if>
						</xsl:for-each>
					</xsl:variable>
					<xsl:value-of select="concat('col-lg-12 col-md-12 col-sm-12 col-xs-12', $nonBootstrapClassValues)"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>

		<xsl:copy>
			<xsl:attribute name="class" select="$newClassValue"/>
			<xsl:apply-templates select="@* except @class" mode="#current"/>
			<xsl:apply-templates select="node()" mode="#current"/>
		</xsl:copy>
	</xsl:template>

	<xsl:template match="*[contains(@class, 'sectiontitle')]" mode="generate-topic-toc" priority="8">
		<!--<li class="section-title">-->
			<xsl:variable name="nodeId" select="ancestor-or-self::*[@id][1]/@id"/>
			<!--<xsl:variable name="parrentId" select="../@id"/>-->
			<a href="#{$nodeId}" data-tocid="{$nodeId}">
				<xsl:apply-templates mode="copy-topic-title"/>
			</a>
		<!--</li>-->
	</xsl:template>

	<xsl:template match="*[contains(@class, 'sectiontitle')][contains(@class, 'tasklabel')]" mode="generate-topic-toc" priority="9">
		<li class="section-title">
			<xsl:variable name="nodeId" select="ancestor-or-self::*[@id][1]/@id"/>
			<!--<xsl:variable name="parrentId" select="../@id"/>-->
			<a href="#{$nodeId}" data-tocid="{$nodeId}">
				<xsl:apply-templates mode="copy-topic-title"/>
			</a>
		</li>
	</xsl:template>

	<xsl:template match="*[contains(@class, 'nested') and not(contains(@class, 'nested0'))]"
				  priority="10" mode="generate-topic-toc">
		<!--<li class="topic-item">-->
		<xsl:apply-templates mode="generate-topic-toc"
							 select="*[contains(@class, 'topictitle')]"/>
		<!--</li>-->
		<xsl:variable name="children">
			<!--<ul>-->
			<xsl:apply-templates mode="generate-topic-toc"
								 select="*[not(contains(@class, 'topictitle'))]"/>
			<!--</ul>-->
		</xsl:variable>
		<xsl:if test="count($children//li) &gt; 0">
			<xsl:copy-of select="$children"/>
		</xsl:if>
	</xsl:template>

	<xsl:template match="*[@class = 'section']" priority="12" mode="generate-topic-toc">
		<li class="section-item">
			<xsl:apply-templates mode="generate-topic-toc"
								 select="*[contains(@class, 'sectiontitle')]"/>
		</li>
		<xsl:variable name="children">
			<!--<ul>-->
			<xsl:apply-templates mode="generate-topic-toc"
								 select="*[not(contains(@class, 'sectiontitle'))]"/>
			<!--</ul>-->
		</xsl:variable>
		<xsl:if test="count($children//li) &gt; 0">
			<xsl:copy-of select="$children"/>
		</xsl:if>
	</xsl:template>

	<xsl:template name="groupRelatedLinks">
		<xsl:param name="relLinks" as="node()*"/>
		<xsl:if test="exists($relLinks)">
			<xsl:element name="{node-name($relLinks[1])}"
						 namespace="{namespace-uri($relLinks[1])}">
				<xsl:copy-of select="$relLinks[1]/@*"/>
				<xsl:for-each-group
						select="$relLinks/div[contains(@class, 'linklist') or contains(@class, 'relinfo')]"
						group-by="
                        (: Group by the link list's title heading (e.g. Related information, Related tasks, etc) :)
                        if (strong) then
                            (string-join(strong//text(), ''))
                        (: If the links list does not have a title, then consider an empty key for grouping the links. :)
                        else
                            ('')">
					<!-- Sort the links by the links list's title heading -->
					<xsl:variable name="firstItem" select="current-group()[1]"/>
					<!-- Merge links lists having the same title in a single list. -->
					<xsl:element name="{node-name($firstItem)}"
								 namespace="{namespace-uri($firstItem)}">
						<xsl:copy-of select="$firstItem/@*"/>
						<xsl:if test="current-grouping-key() != ''">
							<!-- The links list title heading -->
							<span class="related_link-header">
								<xsl:copy-of select="$firstItem/strong"/>
							</span>
							<!--<br/>-->
						</xsl:if>
						<!-- Copy the related links for the current group -->
						<xsl:copy-of
								select="current-group()//*[contains(@class, 'related_link')]"/>
					</xsl:element>
				</xsl:for-each-group>
			</xsl:element>
		</xsl:if>
	</xsl:template>

	<xsl:template match="@href" mode="copyNavigationLinks">
		<xsl:attribute name="href" select="if(contains(., '#')) then(substring-before(., '#')) else(.)"/>
	</xsl:template>
</xsl:stylesheet>
